//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeastFreedom.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Kitchen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kitchen()
        {
            this.Menus = new HashSet<Menu>();
            this.Menus1 = new HashSet<Menu>();
        }

        public int KitchenId { get; set; }

        [Required]
        [Display(Name= "Kitchen Name")]
        public string KitchenName { get; set; }

        public Nullable<int> UserId { get; set; }

        [Display(Name = "Working Days")]
        public string WorkingDays { get; set; }

        public DateTime StartTime { get; set; }

        public DateTime CloseTime { get; set; }

        public string Image { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Menu> Menus { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Menu> Menus1 { get; set; }

        [NotMapped]
        [Required]
        [Display(Name = "Working Days")]
        public string[] selectedDays { get; set; }

        [NotMapped]
        [Required]
        [Display(Name = "Starting Time")]
        public string timeStart { get; set; }

        [NotMapped]
        [Required]
        [Display(Name = "Closing Time")]
        public string timeClose { get; set; }

    }
}
