//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeastFreedom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitchen
    {
        public int KitchenId { get; set; }
        public string KitchenName { get; set; }
        public Nullable<int> UserId { get; set; }
        public string WorkingDays { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> CloseTime { get; set; }
        public byte[] Image { get; set; }
    }
}
