//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeastFreedom.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Menu()
        {
            this.Orders = new HashSet<Order>();
        }

        public int MenuId { get; set; }
        public Nullable<int> KitchenId { get; set; }

        [Required]
        [Display(Name = "Dish Name")]
        public string ItemName { get; set; }

        [Display(Name = "Vegeterian, Vegan, Neither")]
        public string VeganFriendly { get; set; }

        [Display(Name = "Menu Type")]
        public string MenuType { get; set; }

        public string Ingredients { get; set; }

        public Nullable<decimal> Price { get; set; }

        public string Image { get; set; }
        public virtual Kitchen Kitchen { get; set; }
        public virtual Kitchen Kitchen1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
